name: Production Env

on:
  push:
    branches:
      - prod

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "20.10"
          cache: 'npm'
      - name: Install Package
        run: yarn install
      - name: Unit Test
        run: yarn run test
      - name: Build Code
        run: yarn build
      - name: Version Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
      - name: Create A GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: ./dist

  docker-build:
    runs-on: ubuntu-latest
    needs: deployment
    steps:
      - uses: actions/checkout@v4
      - name: Tag Version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN }} 
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfiles/prod.dockerfile
          push: true
          tags: saddamsatria/react-ts-boilerplate:${{steps.tag_version.outputs.new_tag}}